package com.example.opencontrol.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val PrimaryLidht = Color(0xFF6650a4)
val ScondaryLight = Color(0xFF625b71)
val TertiaryLight = Color(0xFF7D5260)

val TestGreen = Color(0xFF18FF00)


val SelectedTab = Color(0xFFE35036)
val UnSelectedTab = Color(0xFFD6D9DF)
val GreyDivider = Color(0xFFC2C2C2)
val LightGreyBorder = Color(0xFFE0E0E0)
val GreyText = Color(0xFF7A7A7A)
val GreyBackground = Color(0xFFF4F4F4)
val WeeklyCalendarSelectedDateBackground = Color(0xFFE7EBFF)
val WeeklyCalendarSelectedDateText = Color(0xFF455CC7)
val OrangeBackground = Color(0x4FFFE0DB)
val OrangeMain = Color(0xFFE35036)
val OrangeMainTransparent73 = Color(0xBAE35036)
val Invisible = Color(0x0)


val md_theme_light_primary = Color(0xFFA42491)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD7F0)
val md_theme_light_onPrimaryContainer = Color(0xFF3A0032)
val md_theme_light_secondary = Color(0xFF6F5767)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF9DAEC)
val md_theme_light_onSecondaryContainer = Color(0xFF281623)
val md_theme_light_tertiary = Color(0xFF933E82)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD7F0)
val md_theme_light_onTertiaryContainer = Color(0xFF3A0032)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1A1D)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1A1D)
val md_theme_light_surfaceVariant = Color(0xFFEFDEE6)
val md_theme_light_onSurfaceVariant = Color(0xFF4F444A)
val md_theme_light_outline = Color(0xFF81737B)
val md_theme_light_inverseOnSurface = Color(0xFFF8EEF1)
val md_theme_light_inverseSurface = Color(0xFF342F32)
val md_theme_light_inversePrimary = Color(0xFFFFACE7)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFFA42491)
val md_theme_light_outlineVariant = Color(0xFFD2C2CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFACE7)
val md_theme_dark_onPrimary = Color(0xFF5E0053)
val md_theme_dark_primaryContainer = Color(0xFF850075)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD7F0)
val md_theme_dark_secondary = Color(0xFFDCBED0)
val md_theme_dark_onSecondary = Color(0xFF3E2A38)
val md_theme_dark_secondaryContainer = Color(0xFF56404F)
val md_theme_dark_onSecondaryContainer = Color(0xFFF9DAEC)
val md_theme_dark_tertiary = Color(0xFFFFACE7)
val md_theme_dark_onTertiary = Color(0xFF5B0750)
val md_theme_dark_tertiaryContainer = Color(0xFF772569)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD7F0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1A1D)
val md_theme_dark_onBackground = Color(0xFFEAE0E3)
val md_theme_dark_surface = Color(0xFF1F1A1D)
val md_theme_dark_onSurface = Color(0xFFEAE0E3)
val md_theme_dark_surfaceVariant = Color(0xFF4F444A)
val md_theme_dark_onSurfaceVariant = Color(0xFFD2C2CA)
val md_theme_dark_outline = Color(0xFF9B8D94)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1A1D)
val md_theme_dark_inverseSurface = Color(0xFFEAE0E3)
val md_theme_dark_inversePrimary = Color(0xFFA42491)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFACE7)
val md_theme_dark_outlineVariant = Color(0xFF4F444A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFFA2228F)
